### ISSUE TITLE
Add Snake Game in python

### ISSUE THREAD

**Issue by abhaygzb15** [mihir5297/Hactoberfest-2023#12]
@mihir5297 It would be grateful if you could assign this issue to me under hactoberfest label.

**Comment by mihir5297** [comment]
@abhaygzb15 Hey Abhay, Sorry to tell you, but all the PR's in this repo has been excluded by Hacktoberfest. I don't know what was the issue. So please rather than contributing here you can check any other repo. Hope for the best.
